### ISSUE TITLE
Fatal error on the Tasks Timeline page

### ISSUE THREAD

**Issue by royvanos** [wyomind/cronscheduler#1]
Hi Wyomind!

When trying to open the **Tasks Timeline** page we get a fatal error:

![selection_100](https://user-images.githubusercontent.com/5882109/30918796-dcb95e5c-a39f-11e7-95b4-c8c1d8318c19.png)

We're using Magento 2.1.9 and PHP 7.0.22, if you need any more information, please ask!

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Wyomind/cronscheduler,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment]
Hey @royvanos !
You should try to increase the php memory limit
