### ISSUE TITLE
Please update Packagist service hook

### ISSUE THREAD

**Issue by chefbuitenhuis** [wyomind/cronscheduler#13]
Could you update the packagist service hook? As the latest version available through packagist is 1.3.0 while the latest tag is 1.3.0.1.

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Wyomind/cronscheduler,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment]
We didn't make the extension available on packagist.
Latest version available on: https://www.wyomind.com and/or https://repo.wyomind.com
