### ISSUE TITLE
Error when running setup:di:compile

### ISSUE THREAD

**Issue by andrewkett** [wyomind/cronscheduler#2]
Errors during compilation:
	Wyomind\CronScheduler\Plugin\Cron\Observer\ProcessCronQueueObserverM21
		Incompatible argument type: Required type: \Magento\Framework\Stdlib\DateTime\DateTime. Actual type: \Magento\Framework\Stdlib\DateTime\TimezoneInterface; File:
/var/www/src/vendor/wyomind/cronscheduler/Plugin/Cron/Observer/ProcessCronQueueObserverM21.php

	Wyomind\CronScheduler\Plugin\Cron\Observer\ProcessCronQueueObserverM20
		Incompatible argument type: Required type: \Magento\Framework\Stdlib\DateTime\DateTime. Actual type: \Magento\Framework\Stdlib\DateTime\TimezoneInterface; File:
/var/www/src/vendor/wyomind/cronscheduler/Plugin/Cron/Observer/ProcessCronQueueObserverM20.php

	Wyomind\CronScheduler\Ui\DataProvider\JobProvider
		Incompatible argument type: Required type: string. Actual type: \Wyomind\CronScheduler\Ui\DataProvider\type; File:
/var/www/src/vendor/wyomind/cronscheduler/Ui/DataProvider/JobProvider.php

	Wyomind\CronScheduler\Ui\DataProvider\TaskProvider
		Incompatible argument type: Required type: string. Actual type: \Wyomind\CronScheduler\Ui\DataProvider\type; File:
/var/www/src/vendor/wyomind/cronscheduler/Ui/DataProvider/TaskProvider.php

Total Errors Count: 4

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Wyomind/cronscheduler,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by wyomind** [comment]
fixed in 1.0.1.5
