### ISSUE TITLE
Document how to install via Github

### ISSUE THREAD

**Issue by erikhansen** [wyomind/cronscheduler#3]
There are currently no documented instructions for how to install via Github. I'd recommend adding some. You can reference this readme I wrote here: https://github.com/turnto/magento2-turnto-socialcommerce/#installation-instructions

In order for the instructions like that to work, you'll need to add this extension to Packagist. Alternatively, you _could_ have the user add this Github repo as a Composer repository, but that's not ideal. 

Commands if you don't add to Packagist;

```
composer config repositories.wyomind/cronscheduler git https://github.com/wyomind/cronscheduler.git
composer require wyomind/cronscheduler
```
  
Commands if you do add to Packagist:

```
composer require wyomind/cronscheduler
```

**Comment by wyomind** [comment]
-- Please reply above this line --

Hey Wyomind/cronscheduler,

Thank you for your message.

 Your request has been correctly submitted.
     
 We’ll be getting back to you as soon as possible!

 Best Regards,
 The Wyomind Team

**Comment by Vedrillan** [comment]
Or even better, submit this repo to https://packagist.org

**Comment by erikhansen** [comment]
@wyomind Can you document this in your readme soon?

**Comment by wyomind** [comment]
to install the module using composer you need to use http://repo.wyomind.com

**Comment by erikhansen** [comment]
@wyomind Hm… that's actually not accurate. The first set of commands I documented above work just fine for me.

My main point is that you should document the Composer install instructions in the readme of this repo.

**Comment by wyomind** [comment]
This github repository purpose is not to be the main place to get the module
